image: ruby:2.6.5

variables:
  CAP_USER: "deployer"
  BUNDLE_CACHE: "vendor/bundle/"
  RAILS_ENV: "test"
  CI: "true"

services:
  - memcached:1.4

before_script:
  - bundle install
  - rails db:create
  - rails db:migrate

stages:
  - test
  - deploy

rspec:
  stage: test
  script:
    - bundle exec rspec --profile

rubocop:
  stage: test
  script:
    - bundle exec rubocop
  allow_failure: true
