image: ruby:2.6.5

variables:
  CAP_USER: "deployer"
  RAILS_ENV: "docker"
  CI: "true"
  MYSQL_ALLOW_EMPTY_PASSWORD: "true"

services:
  - mysql:5.6

before_script:
  - gem install bundler:2.1.4
  - bundle install
  - rails db:create
  - rails db:migrate

stages:
  - test
  - deploy

rspec:
  stage: test
  script:
    - bundle exec rspec --profile

rubocop:
  stage: test
  script:
    - bundle exec rubocop
  allow_failure: true
