image: sibakoro/rspec-ci

variables:
  CAP_USER: "deployer"
  RAILS_ENV: "test"
  CI: "true"
  MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  DATABASE_HOST_TEST: "mysql"

services:
  - mysql:5.6

before_script:
  - gem install bundler:2.1.4
  - bundle install
  - rails db:create
  - rails db:migrate
  - rails webpacker:install
  - RAILS_ENV=test bundle exec rails webpacker:compile

stages:
  - test
  - deploy

rspec:
  stage: test
  script:
    - bundle exec rspec --profile

rubocop:
  stage: test
  script:
    - bundle exec rubocop
  allow_failure: true
