version: "3"

services:
  web:
    image: 052173906758.dkr.ecr.ap-northeast-1.amazonaws.com/sbkn-blog
    command: bash -c "yarn install && rails s -p 3000 -b '0.0.0.0'"
    environment:
      MYSQL_USER: sibakeny
      MYSQL_PASSWORD: d156d156
      MYSQL_HOST: sb-develop.chg7n0luxaan.ap-northeast-1.rds.amazonaws.com
      TZ: "Japan"
    ports:
      - "80:3000"
    tty: true
    deploy:
      resources:
        limits:
          memory: 3g
    logging:
      driver: awslogs
      options:
        awslogs-group: sbkn-blog-production
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: web
