version: "3"

services:
  web:
    image: 052173906758.dkr.ecr.ap-northeast-1.amazonaws.com/sbkn-blog
    command: bash -c "yarn install && pumactl start"
    environment:
      MYSQL_USER: sibakeny
      MYSQL_PASSWORD: d156d156
      MYSQL_HOST: sb-develop.chg7n0luxaan.ap-northeast-1.rds.amazonaws.com
      RAILS_LOG_TO_STDOUT: "ON"
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      TZ: "Japan"
    tty: true
    deploy:
      resources:
        limits:
          memory: 3g
    ports:
      - 0:3000
    logging:
      driver: awslogs
      options:
        awslogs-group: sbkn-blog-production
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: web

  # nginx:
  #   image: 052173906758.dkr.ecr.ap-northeast-1.amazonaws.com/sbkn-blog-nginx
  #   volumes:
  #     - public-data:/sbkn_blog/public
  #     - tmp-data:/sbkn_blog/tmp
  #   ports:
  #     - 0:80
  #   links:
  #     - web
  #   depends_on:
  #     - web
  #   logging:
  #     driver: awslogs
  #     options:
  #       awslogs-group: sbkn-blog-production
  #       awslogs-region: ap-northeast-1
  #       awslogs-stream-prefix: nginx

volumes:
  public-data:
  tmp-data: