default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: localhost
  port: 3306
  username: root
  password:
  database: sbkn_blog_development

test:
  <<: *default
  host: localhost
  port: 3306
  username: root
  password:
  database: sbkn_blog_test

docker:
  adapter: mysql2
  pool: 5
  encoding: utf8
  host: mysql
  database: ci_test
  username: root
  password:
